### ISSUE TITLE
Kanban Board setup

### ISSUE THREAD

**Issue by redwing555** [redwing555/SpaceX-Project#25]
- [Link to react group project .](https://github.com/redwing555/SpaceX-Project/projects/1)
- We are two people working on this project:  @Gambit142,  @redwing555.

 **Note**:  We kept the **dragon's cards** because we agreed to work on it when we are finished with the actual requirements of the project .

**Comment by omar-labana** [comment]
Hi @redwing555 and @Gambit142, 

Excellent work so far planning your project! 👌
You have implemented almost all the required features. ✔️ 
There are some cases that you need to adjust but you are almost done! 😀

## Required Changes ♻️
- [ ] Since you are working on this project as a pair, all cards with `Team3` prefix on the template should be removed from your copy of the template. **Number of cards in Backlog should be equal to 17.**

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
_N/A_

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Gambit142** [comment]
Hi @omar-labana, 

Thanks for the feedback, I understand your viewpoint but we included in the description of this issue that we would like to keep it because we would want to implement the dragon section of the project after Microverse hours preferably during the weekend. We would need the details of the cards to implement them.

Kindly permit us to keep all dragon-related cards in this project.

Thank you once again 👍

**Comment by omar-labana** [comment]
Hi @redwing555 and @Gambit142,

I see that you decided to implement the dragon section of the project together for a completely professional project.
Your project is complete!  There is nothing else to say other than... it's time to start your project! :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by redwing555** [comment]
Hi @omar-labana,

Thank you for the review, and happy coding 🤝 

Kindly,
